services:
  - type: web
    name: premium-hair-backend-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: premium-hair-ecommerce-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        sync: false
      - key: ADMIN_URL
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: LOGIN_RATE_LIMIT_MAX
        value: 5
      - key: BCRYPT_ROUNDS
        value: 12

databases:
  - name: premium-hair-ecommerce-db
    databaseName: premium_hair_ecommerce
    user: premium_hair_user
    plan: free
